services:
    app:
      image: smart-money
      container_name: smart-money
      ports:
        - "8081:8080"
        - "5005:5005"
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/smart-money
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=postgres
        - SPRING_PROFILES_ACTIVE=docker
      depends_on:
        db:
          condition: service_healthy
    db:
      image: postgres:15
      container_name: smart-money-db
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: smart-money
      volumes:
        - ./db-data:/var/lib/postgresql/data
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres" ]
        interval: 10s
        timeout: 5s
        retries: 5

volumes:
    db-data:
